#!/bin/sh
#
# Generates a ZAP Automation Framework plan on standard output.
#
# Usage: build-plan.sh <passive|crawl|active> <environment> [targets.json] [report-prefix]
#
# Three levels of increasing invasiveness, each one including the previous:
#   passive : replays the declared "paths", with GET. No side effect.
#   crawl   : + spider and AJAX spider, without form submission.
#   active  : + form submission and active scanner (real attacks),
#             excludePaths then taking the sensitive routes out of scope.
#
# Schema of targets.json (dast_scan/targets.json by default):
#   environments  : one environment per key, with baseUrl (where {sub} is replaced by
#                   the subdomain), the duration caps in minutes spiderMaxMins,
#                   spiderAjaxMaxMins and activeScanMaxMins, and reportRisks (levels
#                   kept in the reports, all of them by default).
#   sites         : scanned subdomains; paths = routes replayed with GET,
#                   ajaxSpider = site additionally explored by the AJAX spider.
#   excludePaths  : regexes taken out of scope in active mode, for the routes that are
#                   destructive or that trigger emails.
#
# Two more files shape the plan:
#   dast_scan/alert-filters.json : the baseline, turned into an alertFilter job so that an
#                   arbitrated alert stops failing the build while staying in the report.
#   dast_scan/scripts/*.js       : home-made scan rules, inlined below.
#
set -eu

mode=${1:?"missing mode (passive|crawl|active)"}
env_name=${2:?"missing environment (see .environments in targets.json)"}
targets=${3:-"$(dirname "$0")/targets.json"}
scripts_dir="$(dirname "$0")/scripts"
filters_file="$(dirname "$0")/alert-filters.json"

command -v jq >/dev/null 2>&1 || { echo "build-plan.sh: jq is required" >&2; exit 1; }
[ -f "$targets" ] || { echo "build-plan.sh: targets file not found ($targets)" >&2; exit 1; }
jq empty "$targets" 2>/dev/null || { echo "build-plan.sh: invalid JSON ($targets)" >&2; exit 1; }

case "$mode" in passive|crawl|active) ;; *) echo "build-plan.sh: unknown mode ($mode)" >&2; exit 1 ;; esac

base_url=$(jq -r --arg env "$env_name" '.environments[$env].baseUrl // empty' "$targets")
[ -n "$base_url" ] || {
    echo "build-plan.sh: unknown environment ($env_name). Known: $(jq -r '.environments | keys | join(", ")' "$targets")" >&2
    exit 1
}

spider_max_mins=$(jq -r --arg env "$env_name" '.environments[$env].spiderMaxMins // 5' "$targets")
ajax_max_mins=$(jq -r --arg env "$env_name" '.environments[$env].spiderAjaxMaxMins // 2' "$targets")
active_max_mins=$(jq -r --arg env "$env_name" '.environments[$env].activeScanMaxMins // 10' "$targets")
report_risks=$(jq -r --arg env "$env_name" '.environments[$env].reportRisks // [] | join(", ")' "$targets")
fail_on_risk=$(jq -r --arg env "$env_name" '.environments[$env].failOnRisk // "Low"' "$targets")
prefix=${4:-"blackbox-$env_name-$mode"}
context="blackbox"

# The only two switches of the plan: crawl or not, attack or not.
if [ "$mode" = passive ]; then crawl=false; else crawl=true;  fi
if [ "$mode" = active  ]; then attack=true; else attack=false; fi

site_urls() {
    jq -r --arg base "$base_url" '.sites[] | .sub as $sub | ($base | gsub("\\{sub\\}"; $sub))' "$targets"
}

ajax_urls() {
    jq -r --arg base "$base_url" '.sites[] | select(.ajaxSpider) | .sub as $sub | ($base | gsub("\\{sub\\}"; $sub))' "$targets"
}

exclude_paths() { jq -r '.excludePaths[]?' "$targets"; }

# In active mode the excludePaths take routes out of scope: they are then neither attacked
# nor passively analysed, so there is no point in replaying them. ZAP regexes must match
# the whole URL, hence the anchoring.
requestor_urls() {
    jq -r --arg base "$base_url" --argjson filter "$attack" '
        (if $filter then (.excludePaths // []) else [] end) as $excluded
        | .sites[] as $site
        | ($base | gsub("\\{sub\\}"; $site.sub)) as $root
        | $site.paths[]?
        | ($root + .) as $url
        | select([$excluded[] | . as $regex | select($url | test("^" + $regex + "$"))] | length == 0)
        | $url' "$targets"
}

[ -n "$(site_urls)" ] || { echo "build-plan.sh: no entry in .sites" >&2; exit 1; }
[ -n "$(requestor_urls)" ] || { echo "build-plan.sh: no route to replay ($targets: empty \"paths\", or everything excluded by excludePaths)" >&2; exit 1; }

# The context is limited to the declared urls: everything below each of them is included.
cat <<EOF
---
# Plan generated by dast_scan/build-plan.sh ($env_name / $mode) — do not edit by hand.

env:
  contexts:
    - name: $context
      urls:
EOF
site_urls | while IFS= read -r url; do echo "        - \"$url\""; done

if [ "$attack" = true ] && [ -n "$(exclude_paths)" ]; then
    echo '      excludePaths:'
    exclude_paths | while IFS= read -r path; do echo "        - \"$path\""; done
fi

cat <<'EOF'
  parameters:
    failOnError: true
    progressToStdout: true

jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 20
      scanOnlyInScope: true
      enableTags: false
EOF

# The baseline, first of all the jobs that matter: an alert filter only applies to the alerts
# raised after it is registered, so it has to come before any job generating traffic.
# "note" is ours, not ZAP's: it is rendered as a YAML comment above the filter it documents.
alert_filters() {
    [ -f "$filters_file" ] || return 0
    jq -r '
        .filters[]? as $f
        | [$f | del(.note) | to_entries[]] as $entries
        | (if ($f.note // "") != "" then "      # " + $f.note else empty end),
          ( range(0; $entries | length) as $i
            | (if $i == 0 then "      - " else "        " end)
              + $entries[$i].key + ": " + ($entries[$i].value | tojson) )
    ' "$filters_file"
}

if [ -n "$(alert_filters)" ]; then
    cat <<'EOF'

  - type: alertFilter
    alertFilters:
EOF
    alert_filters
fi

# Home-made passive scan rules, registered before any job that generates traffic.
# The code is copied into the plan (inline) rather than mounted into the container: the plan
# stays self-contained, and the one archived by the CI holds the rules that actually ran.
# A passive script is disabled when added, hence the second job that enables it.
for script in "$scripts_dir"/*.js; do
    [ -f "$script" ] || continue
    script_name=$(basename "$script" .js)
    cat <<EOF

  - type: script
    parameters:
      action: add
      type: passive
      engine: "ECMAScript : Graal.js"
      name: $script_name
      inline: |
EOF
    sed 's/^/        /' "$script"
    cat <<EOF

  - type: script
    parameters:
      action: enable
      type: passive
      name: $script_name
EOF
done

cat <<'EOF'

  - type: requestor
    requests:
EOF
requestor_urls | while IFS= read -r url; do
    printf '      - url: "%s"\n        method: GET\n' "$url"
done

if [ "$crawl" = true ]; then
    # A single spider job: its target is the whole context (Target(context) + recurse),
    # the "url" parameter would only add one more seed. One job per site would therefore
    # replay the very same full crawl every time.
    # Forms submitted in active mode only: a crawl must not create an account nor trigger
    # an email as long as attacking has not been accepted.
    cat <<EOF

  - type: spider
    parameters:
      context: $context
      maxDuration: $spider_max_mins
      maxDepth: 10
      threadCount: 5
      postForm: $attack
      processForm: $attack
EOF

    # The AJAX spider really starts from the given url (setStartUri): one job per JS
    # interface, otherwise only the first site of the context would be explored.
    ajax_urls | while IFS= read -r url; do
        cat <<EOF

  - type: spiderAjax
    parameters:
      context: $context
      url: "$url"
      maxDuration: $ajax_max_mins
      maxCrawlDepth: 5
      browserId: firefox-headless
      numberOfBrowsers: 2
      randomInputs: $attack
EOF
    done
fi

cat <<'EOF'

  - type: passiveScan-wait
    parameters:
      maxDuration: 5
EOF

if [ "$attack" = true ]; then
    cat <<EOF

  - type: activeScan
    parameters:
      context: $context
      policy: "Default Policy"
      maxRuleDurationInMins: 1
      maxScanDurationInMins: $active_max_mins
      threadPerHost: 5

  - type: passiveScan-wait
    parameters:
      maxDuration: 5
EOF
fi

# The report is restricted to the declared sites: the AJAX spider browser also loads the
# CDNs referenced by the pages (fonts, icons), which land in the sites tree and would
# otherwise be listed. They are neither crawled nor attacked, the context already limiting
# the scope.
report_job() {
    cat <<EOF

  - type: report
    parameters:
      template: $1
      reportDir: /zap/wrk
      reportFile: "$prefix-{{yyyy-MM-dd-HH-mm-ss}}"
      reportTitle: "ZAP blackbox ($env_name / $mode)"
      reportDescription: "Unauthenticated scan of the public routes of the 4 subdomains."
      displayReport: false
EOF
    if [ -n "$report_risks" ]; then
        echo "    risks: [$report_risks]"
    fi
    echo '    sites:'
    site_urls | while IFS= read -r url; do echo "      - \"$url\""; done
    # Still produces the reports if a previous job interrupts the plan.
    echo '    alwaysRun: true'
}

# The -plus template adds the passingrules (the ~110 passive and active rules that ran
# without finding anything), statistics and params sections, plus the requests and the
# responses of every instance: the report tells what was analysed, not only what alerted.
# It weighs about 7 times more than the standard template.
report_job traditional-html-plus
report_job traditional-json

# The gate. ZAP itself exits 0 whatever it finds, so this job is what turns an alert into a red
# pipeline. Alerts requalified as "False Positive" by the alertFilter job are skipped by ZAP here
# (ExitStatusJob ignores CONFIDENCE_FALSE_POSITIVE), which is what makes the baseline work.
# alwaysRun so that the status is still set when an earlier job interrupts the plan.
cat <<EOF

  - type: exitStatus
    parameters:
      errorLevel: "$fail_on_risk"
      warnLevel: "Informational"
    alwaysRun: true
EOF
